### ISSUE TITLE
Error when trying to view the results - any ideas?

### ISSUE THREAD

**Issue by saf001** [ColdTrick/poll#6]
Chart.min.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
require.js:14 Uncaught Error: Script error for "chartjs"
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js:17)
    at HTMLScriptElement.onScriptError (require.js:117)

Thank you!

**Comment by jeabakker** [comment]
How did you install the plugin?
- downloaded from the Elgg community
- using composer
- downloaded directly from GitHub

It sounds like you'r missing the `chart.js` files, most likely because you got the plugin directly from GitHub. You need to run `composer install` in the plugin directly to get the files, or download the correct zip file from the Elgg community / GitHub releases tab
